name: smart_assistant
description: 智能桌面助手应用程序

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.7
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  path_provider: ^2.1.1
  desktop_window: ^0.4.0
  flutter_markdown: ^0.6.18
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.0
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
