name: Windows Build

on:
  push:
    branches: [ main, devin/1735116746-setup-github-actions-v2 ]
  pull_request:
    branches: [ main, devin/1735116746-setup-github-actions-v2 ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows
  BUILD_TYPE: Release
  SOLUTION_FILE_PATH: SmartAssistant.sln
  MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe"
  CMAKE_GENERATOR: "Visual Studio 17 2022"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/vcpkg/installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git ${{ env.VCPKG_ROOT }}
        cd ${{ env.VCPKG_ROOT }}
        git checkout 2023.12.12
        .\bootstrap-vcpkg.bat -disableMetrics

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Setup VSBuild Tools
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Install Dependencies
      run: |
        cd ${{ env.VCPKG_ROOT }}
        .\vcpkg integrate install
        echo "::group::Installing C++ Dependencies"
        
        # Install C++ dependencies
        .\vcpkg install --triplet=x64-windows `
          openssl `
          boost[system,filesystem,thread] `
          sqlite3 `
          websocketpp `
          gtest
        
        cd ${{ github.workspace }}
        echo "::endgroup::"
        echo "::group::Installing NuGet Packages"
        dotnet restore SmartAssistant.UI/SmartAssistant.UI.csproj
        dotnet restore SmartAssistant.UI.Tests/SmartAssistant.UI.Tests.csproj
        echo "::endgroup::"

    - name: Build Core Library
      run: |
        cmake -B build -S . `
          -G "${{ env.CMAKE_GENERATOR }}" `
          -A x64 `
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" `
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DCMAKE_PREFIX_PATH="${{ env.VCPKG_ROOT }}/installed/x64-windows" `
          -DBUILD_TESTING=OFF
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel --verbose

    - name: Build UI
      run: |
        msbuild SmartAssistant.sln /p:Configuration=${{ env.BUILD_TYPE }} /p:Platform=x64

    - name: Run Tests
      run: |
        cd build
        ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
        cd ..
        dotnet test SmartAssistant.UI.Tests/SmartAssistant.UI.Tests.csproj

    - name: Create Installer
      run: |
        cd installer
        .\build_installer.ps1 -Configuration ${{ env.BUILD_TYPE }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SmartAssistant-Windows
        path: |
          installer/bin/${{ env.BUILD_TYPE }}/SmartAssistant-Setup.msi
          build/${{ env.BUILD_TYPE }}/SmartAssistant.Core.dll
          SmartAssistant.UI/bin/${{ env.BUILD_TYPE }}/net6.0-windows/SmartAssistant.UI.exe
