name: Windows Build

on:
  push:
    branches: [ main, 'devin/*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        
    - name: Setup VSBuild Tools
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
        
    - name: Install Dependencies
      shell: pwsh
      run: |
        Set-Location -Path "smart-assistant"
        flutter config --enable-windows-desktop
        flutter pub get
        
    - name: Build Flutter App
      shell: pwsh
      run: |
        Set-Location -Path "smart-assistant"
        flutter config --enable-windows-desktop
        flutter build windows --release
        
    - name: Run Tests
      shell: pwsh
      run: |
        Set-Location -Path "smart-assistant"
        flutter test
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: smart-assistant/build/windows/runner/Release/
